import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  PrincipalStyle: {
    flex: 1,
    backgroundColor: '#EBEBEF',
    alignItems: 'center',
    position: 'relative',
    justifyContent: 'flex-start',
  },
  PrimaryText: {
    color: '#434254',
    fontSize: 25,
  },
  SecondaryText: {
    color: '#000',
    fontSize: 30,
  },
  styleViewImage: {
    flex: 1,
    backgroundColor: '#EBEBEF',
  },
  styleViewImage2: {
    flex: 0.5,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    paddingTop: '-15%',
    paddingLeft: '20%',
  },
  imageStyle: {
    resizeMode: 'contain',
    height: '100%',
    width: '40%',
  },
  imageStyle2: {
    resizeMode: 'contain',
    height: '100%',
    width: '40%',
  },
  InputsStyleDivs: {
    alignItems: 'center',
    position: 'relative',
    justifyContent: 'flex-start',
  },
  tIStyle: {
    textAlign: 'left',
    fontSize: 20,
    width: '50%',
    height: '15%',
    margin: 5,
    borderColor: '#243572',
    borderBottomWidth: 2,
  },
  butonStyle: {
    marginTop: 20,
    width: '50%',
    height: '10%',
    backgroundColor: '#243572',
    paddingTop: 5,
    alignItems: 'center',
    borderRadius: 5,
  },
  FontButonStyle: {
    color: '#fff',
    fontSize: 20,
  },
  otherOptios: {
    flex: 1,
    alignItems: 'center',
    position: 'relative',
    justifyContent: 'flex-start',
    paddingTop: '10%',
  },
  butonStyleForPassword: {
    marginTop: 40,
    marginBottom: 20,
    width: '90%',
    height: 50,
    backgroundColor: '#EBEBEF',
    padding: 10,
    alignItems: 'center',
  },
  FontButonStyleForPassword: {
    color: '#434254',
    fontSize: 20,
  },
  butonStyleForRegister: {
    marginTop: 20,
    width: '60%',
    height: 45,
    backgroundColor: '#243572',
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 5,
    alignItems: 'center',
    borderRadius: 40,
  },
  SeconViewOfRecover: {
    flex: 0.2,
    alignItems: 'center',
    marginTop: 40,
    padding: 50,
    textAlign: 'center',
  },
  textOfSeconView: {
    textAlign: 'center',
    color: '#434254',
    fontSize: 25,
  },
  ViewStyleForMain: {
    borderColor: '#000',
    alignItems: 'center',
    position: 'relative',
    top: '30%',
    marginBottom: 0,
    paddingLeft: 50,
    paddingRight: 50,
  },
  styleForMainText: {
    textAlign: 'justify',
    color: '#434254',
    fontSize: 18,
  },
  imageStyleFroMain: {
    position: 'absolute',
    height: 155,
    width: 100,
    left: '20%',
    top: 30,
  },
  imageStyle2ForMain: {
    position: 'absolute',
    height: 160,
    width: 110,
    left: '50%',
    top: 25,
  },
  butonsView: {
    top: '40%',
  },
  buton1: {
    marginTop: 20,
    width: 180,
    height: 60,
    left: 20,
    backgroundColor: '#243572',
    paddingTop: 15,
    alignItems: 'center',
    borderRadius: 5,
    top: 10,
  },
  buton2: {
    position: 'absolute',
    marginTop: 20,
    width: 180,
    height: 60,
    left: 210,
    backgroundColor: '#243572',
    paddingTop: 15,
    alignItems: 'center',
    borderRadius: 5,
    top: 10,
  },
  buton3: {
    position: 'absolute',
    marginTop: 20,
    width: 180,
    height: 60,
    left: 210,
    backgroundColor: '#243572',
    paddingTop: 15,
    alignItems: 'center',
    borderRadius: 5,
    top: 90,
  },
});

export default styles;
